---
title: "Rossmann Regression"
author: "빨간데이터"
date: "2018년 8월 6일"
output: html_document
---


# 1. Rossmann Store 
### 1.1 개요

독일에 위치하는 1,115개 Rossmann가게의 
6주동안의 매출액을 예측하는 프로젝트임.  

2013년 1월 1일부터 2015년 7월 31일까지
약 2년 6개월간의 1,115개 가게 데이터로부터
2015년 8월 1부터 2015년 9월 17일까지 
약 6주기간 동안의 가게 매출액을 예측할 예정임

### 1.2 데이터셋 정보



# 2. 분석
### 2.1 상관계수 분석

train 데이터에서 구하고자 하는 종속변수, 매출액(sales) 변수를 제외한 나머지 수치형 변수간의 상관관계를 회귀분석 전에 선행함.

```{r echo=FALSE}
library(lubridate)
library(dplyr)
library(ggplot2)
library(dummies)
library(psych)
library(corrplot)
library(nortest)
library(car)

setwd("d:/FastCampus/Rossman/")

options(scipen = 100)
train <- read.csv("train.csv", header = TRUE, stringsAsFactors = FALSE)
head(train)
summary(train)

test <- read.csv("test.csv", header = TRUE, stringsAsFactors = F)
head(test)
summary(test)

store <- read.csv("store.csv", header = T, stringsAsFactors = F)
head(store)
summary(store)
```
```{r echo=FALSE}
train <- merge(train, store, by = "Store", all.x = TRUE) # train과 store를 "Store" 기준으로 합치기

test <- merge(test, store, by = "Store", all.x = TRUE) # test과 store를 "Store" 기준으로 합치기

str(train)
head(train)

```



```{r}
# datetime의 year, month, day를 따로 빼서 column만들기
train <- train %>% mutate(year = year(Date), month = month(Date), day = day(Date))

head(train)

test <- test %>% mutate(year = year(Date), month = month(Date), day = day(Date))

head(test)
ncol(train)
ncol(test)
colnames(train)
```

```{r}

# 각 데이터의 NA를 각 column의 평균값으로 채우기

train$PromoInterval <- as.factor(train$PromoInterval)

for(i in 1:ncol(train)){
  train[is.na(train[,i]), i] <- mean(train[,i], na.rm = TRUE)
}

test$PromoInterval <- as.factor(test$PromoInterval)

for(i in 1:ncol(test)){
  test[is.na(test[,i]), i] <- mean(test[,i], na.rm = TRUE)
}

```

```{r}
# 더미변수 만들기

train <- train %>% mutate(StoreTypeb = ifelse(StoreType == 'b', 1, 0),
                          StoreTypec = ifelse(StoreType == 'c', 1, 0),
                          StoreTyped = ifelse(StoreType == 'd', 1, 0))


train <- train %>% mutate(StateHolidaya = ifelse(StateHoliday == 'a', 1, 0),
                          StateHolidayb = ifelse(StateHoliday == 'b', 1, 0),
                          StateHolidayc = ifelse(StateHoliday == 'c', 1, 0))

train <- train %>% mutate(Assortmentb = ifelse(Assortment == 'b', 1, 0),
                            Assortmentc = ifelse(Assortment == 'c', 1, 0))


levels(train$PromoInterval) <- c(0, 2, 1, 3)
train <- train %>% mutate(PromoIntervalJ = ifelse(PromoInterval == '1', 1, 0),
                            PromoIntervalF = ifelse(PromoInterval == '2', 1, 0),
                            PromoIntervalM = ifelse(PromoInterval == '3', 1, 0))


test <- test %>% mutate(StoreTypeb = ifelse(StoreType == 'b', 1, 0),
                          StoreTypec = ifelse(StoreType == 'c', 1, 0),
                          StoreTyped = ifelse(StoreType == 'd', 1, 0))


test <- test %>% mutate(StateHolidaya = ifelse(StateHoliday == 'a', 1, 0),
                          StateHolidayb = ifelse(StateHoliday == 'b', 1, 0),
                          StateHolidayc = ifelse(StateHoliday == 'c', 1, 0))

test <- test %>% mutate(Assortmentb = ifelse(Assortment == 'b', 1, 0),
                          Assortmentc = ifelse(Assortment == 'c', 1, 0))


levels(test$PromoInterval) <- c(0, 2, 1, 3)
test <- test %>% mutate(PromoIntervalJ = ifelse(PromoInterval == '1', 1, 0),
                          PromoIntervalF = ifelse(PromoInterval == '2', 1, 0),
                          PromoIntervalM = ifelse(PromoInterval == '3', 1, 0))

```

```{r}
# Customers를 종속변수로 회기 모델 만들기

rossmann.model <- lm(Customers ~ Open + StoreTypeb, data = train)

summary(rossmann.model)
```

```{r}

# 다중공선성(Multicollinearity) 구하기

car::vif(rossmann.model)
```


```{r}
# 독립변수들의 영향력 크기의 비교

lm.beta1 <- lm.beta::lm.beta(rossmann.model)

coeffi1 <- sort(abs(lm.beta1$coefficients), decreasing = T)

barplot(coeffi1[-1])
```

```{r}
# test의 Customers 값 예측하기

predict(rossmann.model, newdata = test)
test.customers <- matrix(unlist(predict(rossmann.model, newdata = test)), nrow = nrow(test), ncol = 1)

View(test.customers)
```


```{r}
# Customers 예측값 test 에 병합하기

test <- cbind(test, test.customers)
test <- mutate(test, Customers = test.customers)
test$test.customers <- NULL

View(test)
```

```{r}
# Sales를 종속변수로 회기 모델 만들기

rossmann.model1 <- lm(Sales ~ StoreTypeb + Assortmentb, data = train)

summary(rossmann.model1)
```

```{r}
# 다중공선성(Multicollinearity) 구하기

car::vif(rossmann.model1)
```

```{r}

# 독립변수들의 영향력 크기의 비교

lm.beta2 <- lm.beta::lm.beta(rossmann.model1)

coeffi2 <- sort(abs(lm.beta2$coefficients), decreasing = T)

barplot(coeffi2[-1])

```


```{r}
# test의 Sales 값 예측하기

predict(rossmann.model1, newdata = test)
test.sales <- matrix(unlist(predict(rossmann.model1, newdata = test)), nrow = nrow(test), ncol = 1)
```

```{r}
# sample_submission.csv파일 불러오기
ss <- read.csv("sample_submission.csv", header = TRUE, sep = ",", check.names = FALSE)
```


```{r}
# Sales 예측값 sample_submission.csv 에 병합하기

ss <- cbind(ss, test.sales)
ss <- mutate(ss, Sales = test.sales)
ss$test.sales <- NULL

write.csv(ss, "sample_submission.csv", row.names = FALSE)
```





